server.port=8080
spring.application.name=servicio-reactivo
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/tienda_db
spring.r2dbc.username=postgres
spring.r2dbc.password=sa

# Inicializar esquema automáticamente
spring.sql.init.mode=always

# Netty usará por defecto los hilos = número de cores del CPU.
# Puedes ver los hilos en VisualVM.

# Exposición de Métricas para Actuator y Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true