server:
  port: 8080

spring:
  application:
    name: tienda-videojuegos-mvc
  
  # Configuración de Conexión a PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_db
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# Exposición de Métricas
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true